export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';

export const FINAL_TRANSCRIPT = 'FINAL_TRANSCRIPT';
export const INTERIM_TRANSCRIPT = 'INTERIM_TRANSCRIPT';
export const LISTENING_TRANSCRIPT = 'LISTENING_TRANSCRIPT';
